import { Product } from '@/domain'

export const products: Product[] = [
  {
    id: 1,
    title: 'Смартфон Apple iPhone 14',
    description: 'Новейший iPhone с улучшенным экраном и камерой.',
    price: 999,
    image_url: '/images/image_1.webp',
    category: 'Электроника',
  },
  {
    id: 2,
    title: 'Беспроводные наушники Sony',
    description: 'Удобные наушники с шумоподавлением.',
    price: 199,
    image_url: '/images/image_2.webp',
    category: 'Бытовая техника',
  },
  {
    id: 3,
    title: 'Ноутбук Dell XPS 13',
    description: 'Мощный и легкий ноутбук для работы и развлечений.',
    price: 1299,
    image_url: '/images/image_1.webp',
    category: 'Аксессуары',
  },
  {
    id: 4,
    title: 'Смарт-часы Samsung Galaxy Watch 4',
    description: 'Современные смарт-часы с множеством функций.',
    price: 299,
    image_url: '/images/image_2.webp',
    category: 'Электроника',
  },
  {
    id: 5,
    title: 'Телевизор LG OLED65CX',
    description: 'Телевизор с превосходным качеством изображения.',
    price: 1999,
    image_url: '/images/image_1.webp',
    category: 'Бытовая техника',
  },
  {
    id: 6,
    title: 'Игровая приставка PlayStation 5',
    description: 'Консоль нового поколения с невероятной производительностью.',
    price: 499,
    image_url: '/images/image_2.webp',
    category: 'Аксессуары',
  },
  {
    id: 7,
    title: 'Мультиварка Redmond',
    description: 'Универсальная мультиварка для приготовления разнообразных блюд.',
    price: 89,
    image_url: '/images/image_1.webp',
    category: 'Электроника',
  },
  {
    id: 8,
    title: 'Фитнес-трекер Xiaomi Mi Band 5',
    description: 'Умный браслет для отслеживания активности и здоровья.',
    price: 39,
    image_url: '/images/image_2.webp',
    category: 'Бытовая техника',
  },
  {
    id: 9,
    title: 'Кофемашина Nespresso',
    description: 'Автоматическая кофемашина для приготовления эспрессо и капучино.',
    price: 149,
    image_url: '/images/image_1.webp',
    category: 'Аксессуары',
  },
  {
    id: 10,
    title: 'Электросамокат Xiaomi',
    description: 'Складной электросамокат для удобного передвижения по городу.',
    price: 399,
    image_url: '/images/image_2.webp',
    category: 'Электроника',
  },
  {
    id: 11,
    title: 'Водонепроницаемый рюкзак',
    description: 'Прочный и вместительный рюкзак для путешествий и спорта.',
    price: 49,
    image_url: '/images/image_1.webp',
    category: 'Бытовая техника',
  },
  {
    id: 12,
    title: 'Электрическая зубная щетка Philips',
    description: 'Эффективная зубная щетка для ежедневного ухода за зубами.',
    price: 59,
    image_url: '/images/image_2.webp',
    category: 'Аксессуары',
  },
]

export const popular: Product[] = [
  {
    id: 1,
    title: 'Смартфон Apple iPhone 14',
    description: 'Новейший iPhone с улучшенным экраном и камерой.',
    price: 999,
    image_url: '/images/image_1.webp',
    category: 'Электроника',
  },
  {
    id: 2,
    title: 'Беспроводные наушники Sony',
    description: 'Удобные наушники с шумоподавлением.',
    price: 199,
    image_url: '/images/image_2.webp',
    category: 'Бытовая техника',
  },
  {
    id: 3,
    title: 'Ноутбук Dell XPS 13',
    description: 'Мощный и легкий ноутбук для работы и развлечений.',
    price: 1299,
    image_url: '/images/image_1.webp',
    category: 'Аксессуары',
  },
  {
    id: 4,
    title: 'Смарт-часы Samsung Galaxy Watch 4',
    description: 'Современные смарт-часы с множеством функций.',
    price: 299,
    image_url: '/images/image_2.webp',
    category: 'Электроника',
  },
]
